### ISSUE TITLE
Newes version is not working.

### ISSUE THREAD

**Issue by keyboardbored** [ImaDoofus/HousingEditor#20]
Alpha-8 Is not working, I did all right and it not working. When i type /housingeditor it says "Unknown command" Nothing is doesnt works :\

**Comment by ImaDoofus** [comment]
> Alpha-8 Is not working, I did all right and it not working. When i type /housingeditor it says "Unknown command" Nothing is doesnt works :\

It is working for others, make sure the folder is named HousingEditor and not HousingEditor-master 
Check when you do ’/ct modules’ you see HousingEditor with the appropriate description. If there is no description the folder structure might be wrong double check.
Otherwise check ’/ct console js’ for any errors.

Good luck

**Comment by keyboardbored** [comment]
oh thanks, it named housing-master
